export type ComparableSeverity = 'low' | 'medium' | 'high'

export interface ComparableClaimRecord {
  id: string
  vehicleMake: string
  vehicleModel: string
  severity: ComparableSeverity
  damageAreas: string[]
  finalRepairCost: number
  repairDurationDays: number
  shortDescription: string
}

export const MOCK_COMPARABLE_CLAIMS: ComparableClaimRecord[] = [
  {
    id: 'HIST-90011',
    vehicleMake: 'Toyota',
    vehicleModel: 'RAV4',
    severity: 'low',
    damageAreas: ['bumper', 'fender'],
    finalRepairCost: 1180,
    repairDurationDays: 4,
    shortDescription: 'Low-speed parking lot scrape with front bumper and fender scuffing.',
  },
  {
    id: 'HIST-90012',
    vehicleMake: 'Honda',
    vehicleModel: 'Accord',
    severity: 'medium',
    damageAreas: ['rear', 'bumper', 'door'],
    finalRepairCost: 2840,
    repairDurationDays: 8,
    shortDescription: 'Rear impact at stoplight with trunk alignment and rear door blend work.',
  },
  {
    id: 'HIST-90013',
    vehicleMake: 'Ford',
    vehicleModel: 'F-150',
    severity: 'high',
    damageAreas: ['front', 'hood', 'headlight', 'bumper'],
    finalRepairCost: 7425,
    repairDurationDays: 16,
    shortDescription: 'Front-end collision requiring hood, lighting, and structural bracket replacement.',
  },
  {
    id: 'HIST-90014',
    vehicleMake: 'Nissan',
    vehicleModel: 'Altima',
    severity: 'medium',
    damageAreas: ['door', 'fender'],
    finalRepairCost: 2210,
    repairDurationDays: 7,
    shortDescription: 'Sideswipe on driver side with door skin and fender repair.',
  },
  {
    id: 'HIST-90015',
    vehicleMake: 'Chevrolet',
    vehicleModel: 'Malibu',
    severity: 'medium',
    damageAreas: ['rear', 'bumper', 'quarter-panel'],
    finalRepairCost: 3390,
    repairDurationDays: 10,
    shortDescription: 'Rear corner impact with bumper cover and quarter-panel refinishing.',
  },
  {
    id: 'HIST-90016',
    vehicleMake: 'Subaru',
    vehicleModel: 'Outback',
    severity: 'low',
    damageAreas: ['door', 'fender'],
    finalRepairCost: 1360,
    repairDurationDays: 5,
    shortDescription: 'Minor lane-merge contact with cosmetic door and fender damage.',
  },
  {
    id: 'HIST-90017',
    vehicleMake: 'Kia',
    vehicleModel: 'Sportage',
    severity: 'high',
    damageAreas: ['rear', 'bumper', 'hood'],
    finalRepairCost: 6480,
    repairDurationDays: 13,
    shortDescription: 'Multi-point collision with rear and front panel repair required.',
  },
  {
    id: 'HIST-90018',
    vehicleMake: 'Tesla',
    vehicleModel: 'Model 3',
    severity: 'medium',
    damageAreas: ['front', 'bumper', 'headlight'],
    finalRepairCost: 4120,
    repairDurationDays: 11,
    shortDescription: 'Front bumper and headlight replacement with sensor recalibration.',
  },
  {
    id: 'HIST-90019',
    vehicleMake: 'BMW',
    vehicleModel: 'X3',
    severity: 'medium',
    damageAreas: ['rear', 'door', 'bumper'],
    finalRepairCost: 4590,
    repairDurationDays: 12,
    shortDescription: 'Rear passenger door crush and bumper transfer damage.',
  },
  {
    id: 'HIST-90020',
    vehicleMake: 'Toyota',
    vehicleModel: 'Corolla',
    severity: 'low',
    damageAreas: ['front', 'bumper'],
    finalRepairCost: 980,
    repairDurationDays: 3,
    shortDescription: 'Front bumper abrasion with paint and clip replacement.',
  },
  {
    id: 'HIST-90021',
    vehicleMake: 'Mazda',
    vehicleModel: 'CX-5',
    severity: 'medium',
    damageAreas: ['fender', 'door', 'headlight'],
    finalRepairCost: 2985,
    repairDurationDays: 9,
    shortDescription: 'Front-side strike with fender and lamp assembly replacement.',
  },
  {
    id: 'HIST-90022',
    vehicleMake: 'Volkswagen',
    vehicleModel: 'Jetta',
    severity: 'low',
    damageAreas: ['rear', 'bumper'],
    finalRepairCost: 1240,
    repairDurationDays: 4,
    shortDescription: 'Low-speed rear tap with bumper reconditioning and repaint.',
  },
  {
    id: 'HIST-90023',
    vehicleMake: 'Hyundai',
    vehicleModel: 'Tucson',
    severity: 'high',
    damageAreas: ['hood', 'front', 'bumper', 'windshield'],
    finalRepairCost: 8190,
    repairDurationDays: 18,
    shortDescription: 'Front-end and glass damage with extensive parts replacement.',
  },
  {
    id: 'HIST-90024',
    vehicleMake: 'Ford',
    vehicleModel: 'Escape',
    severity: 'medium',
    damageAreas: ['front', 'bumper', 'fender'],
    finalRepairCost: 2675,
    repairDurationDays: 8,
    shortDescription: 'Front quarter impact requiring bumper blend and fender repair.',
  },
]
